In [19]:
import pandas as pd

In [3]:
from pybaseball import batting_stats

In [11]:
df = batting_stats(2014, 2024, qual=1)

In [12]:
# Filter the dataframe to only include rows where the player is Aaron Judge
aaron_judge_df = df[df['Name'] == 'Aaron Judge']

In [13]:
aaron_judge_df

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
155,15640,2024,Aaron Judge,NYY,32,158,559,704,180,85,...,117.5,238.0,0.609,391,0.146,0.267,NaN,NaN,NaN,11.3
167,15640,2022,Aaron Judge,NYY,30,157,570,696,177,87,...,118.4,246.0,0.609,404,0.169,0.287,NaN,NaN,NaN,11.4
257,15640,2017,Aaron Judge,NYY,25,155,542,678,154,75,...,121.1,186.0,0.550,338,0.157,0.290,NaN,NaN,NaN,8.8
509,15640,2021,Aaron Judge,NYY,29,148,550,633,158,95,...,119.0,230.0,0.579,397,0.170,0.283,NaN,NaN,NaN,5.6
480,15640,2018,Aaron Judge,NYY,26,112,413,498,115,66,...,119.9,144.0,0.541,266,0.178,0.316,NaN,NaN,NaN,5.3
280,15640,2023,Aaron Judge,NYY,31,106,367,458,98,45,...,116.9,154.0,0.642,240,0.160,0.298,NaN,NaN,NaN,5.1
560,15640,2019,Aaron Judge,NYY,27,102,378,447,103,57,...,118.1,139.0,0.582,239,0.170,0.317,NaN,NaN,NaN,4.2
669,15640,2020,Aaron Judge,NYY,28,28,101,114,26,14,...,113.1,29.0,0.414,70,0.166,0.306,NaN,NaN,NaN,1.1
5314,15640,2016,Aaron Judge,NYY,24,27,84,95,15,9,...,115.2,25.0,0.581,43,0.179,0.360,NaN,NaN,NaN,-0.2

In [14]:
df_2014 = df

In [16]:
df_2013 = batting_stats(2003, 2013, qual=1)

In [20]:
total_data = pd.concat([df_2013, df_2014], ignore_index=True)

In [21]:
total_data.to_csv("original_data.csv", index=False)

In [25]:
df_2002 = batting_stats(1992, 2002, qual=1)

In [24]:
total_data

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
0,1109,2004,Barry Bonds,SFG,39,147,373,617,135,60,...,NaN,NaN,NaN,0,0.124,0.164,NaN,NaN,NaN,11.9
1,1109,2003,Barry Bonds,SFG,38,130,390,550,133,65,...,NaN,NaN,NaN,0,0.135,0.223,NaN,NaN,NaN,10.2
2,10155,2013,Mike Trout,LAA,21,157,589,716,190,115,...,NaN,0.0,NaN,0,0.200,0.266,NaN,NaN,NaN,10.1
3,10155,2012,Mike Trout,LAA,20,139,559,639,182,117,...,NaN,0.0,NaN,0,0.221,0.293,NaN,NaN,NaN,10.1
4,9166,2012,Buster Posey,SFG,25,148,530,610,178,114,...,NaN,0.0,NaN,0,0.190,0.251,NaN,NaN,NaN,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19928,11376,2014,Michael Choice,TEX,24,86,253,280,46,30,...,NaN,0.0,NaN,0,0.226,0.318,NaN,NaN,NaN,-2.0
19929,12155,2024,Eddie Rosario,- - -,32,91,297,319,52,30,...,110.2,96.0,0.425,226,0.146,0.281,NaN,NaN,NaN,-2.3
19930,3448,2019,Jeff Mathis,TEX,36,88,228,244,36,25,...,105.5,37.0,0.261,142,0.155,0.322,NaN,NaN,NaN,-2.1
19931,11615,2024,Brandon Drury,LAA,31,97,325,360,55,44,...,113.7,87.0,0.352,247,0.175,0.280,NaN,NaN,NaN,-1.9
19932,9272,2018,Chris Davis,BAL,32,128,470,522,79,51,...,111.8,113.0,0.401,282,0.174,0.316,NaN,NaN,NaN,-2.6

In [23]:
unique_values = total_data['Season'].unique()

print(unique_values)

[2004 2003 2013 2012 2007 2011 2005 2008 2009 2010 2006 2024 2022 2018
 2015 2023 2017 2016 2019 2014 2021 2020]

In [26]:
df_1991 = batting_stats(1982, 1991, qual=1)

In [27]:
df_1981 = batting_stats(1972, 1981, qual=1)

In [28]:
df_1971 = batting_stats(1962, 1971, qual=1)

In [29]:
df_1961 = batting_stats(1952, 1961, qual=1)

In [30]:
df_1951 = batting_stats(1942, 1951, qual=1)

In [31]:
df_1941 = batting_stats(1932, 1941, qual=1)

In [32]:
df_1931 = batting_stats(1922, 1931, qual=1)

In [33]:
df_1921 = batting_stats(1912, 1921, qual=1)

In [34]:
df_1911 = batting_stats(1900, 1911, qual=1)

In [35]:
total_data = pd.concat([df_2013, df_2014, df_2002, df_1991, df_1981, df_1971, df_1961, df_1951, df_1941, df_1931, df_1921, df_1911,], ignore_index=True)

In [36]:
df_sorted = total_data.sort_values(by='Season')

In [37]:
unique_values = df_sorted['Season'].unique()

print(unique_values)

[1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913
 1914 1915 1916 1917 1918 1919 1920 1921 1922 1923 1924 1925 1926 1927
 1928 1929 1930 1931 1932 1933 1934 1935 1936 1937 1938 1939 1940 1941
 1942 1943 1944 1945 1946 1947 1948 1949 1950 1951 1952 1953 1954 1955
 1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969
 1970 1971 1972 1973 1974 1975 1976 1977 1978 1979 1980 1981 1982 1983
 1984 1985 1986 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997
 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011
 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024]

In [38]:
df_sorted.to_csv("all_data.csv", index=False)